# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  replicaCount: 1

  image:
    repository: localhost:32000/argocd-web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.4"
